# _config.yml

plugins:
 - jekyll-feed
 - jekyll-remote-theme
 - jekyll-seo-tag

# Build settings
remote_theme: briandrum/optima

# Title & description: https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/usage.md
title: Codified Ordinances of Chagrin Falls, Ohio
author:
  name: Brian Drum
  email: brian@briandrum.com
  twitter: drumforchagrin
description: > # this means to ignore newlines until "show_excerpts:"
  Codified Ordinances of Chagrin Falls, Ohio

header_pages:
  - index.md
  - committees-boards-and-commissions.md

show_excerpts: false
excerpt_separator: <!--more-->
