# _config.yml

# Build settings
remote_theme: briandrum/jekyll-theme-optima

plugins:
 - jekyll-feed
 - jekyll-remote-theme
 - jekyll-seo-tag

# Title & description: https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/usage.md
title: Codified Ordinances of Chagrin Falls, Ohio
author:
  name: Brian Drum
  email: brian@briandrum.com
  twitter: drumforchagrin
description: > # this means to ignore newlines until "show_excerpts:"
  Codified Ordinances of Chagrin Falls, Ohio

permalink: /:title/

show_excerpts: false # set to true to show excerpts on the homepage
excerpt_separator: <!--more-->

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
 - index.md
 - search.md

collections:
  articles:
    output: true
  chapters:
    output: true
  parts:
    output: true
  titles:
    output: false
