# _config.yml

# Build settings
remote_theme: briandrum/jekyll-theme-optima

plugins:
 - jekyll-feed
 - jekyll-remote-theme
 - jekyll-seo-tag

# https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/advanced-usage.md#setting-a-default-image
defaults:
  - scope:
      path: ""
    values:
      image: /assets/images/og-image.png

# Title & description: https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/usage.md
title: The Codified Ordinances of Chagrin Falls, Ohio
author:
  name: Brian Drum
  email: codes@forchagrin.com
description: > # this means to ignore newlines until "show_excerpts:"
  An Unofficial Repository of The Codified Ordinances of Chagrin Falls, Ohio.

permalink: /:title/

show_excerpts: false # set to true to show excerpts on the homepage
excerpt_separator: <!--more-->
future: true # set to true to generate future-date posts

# Plausible analytics: https://plausible.io/
plausible_analytics: codes.forchagrin.com

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
 - index.md
 - search.md

collections:
  articles:
    output: true
  chapters:
    output: true
  parts:
    output: true
  titles:
    output: false
